cat : cat.c getopt.c getopt.h
	cl cat.c getopt.c
cat.c :
	wget https://raw.githubusercontent.com/joshouamel/tools/master/src/cat/cat.c --no-check-certificate
getopt.c :
	wget https://raw.githubusercontent.com/joshouamel/tools/master/src/cat/getopt.c --no-check-certificate
getopt.h :
	wget https://raw.githubusercontent.com/joshouamel/tools/master/src/cat/getopt.h --no-check-certificate
