cat : cat.c getopt.c
	cl cat.c getopt.c
cat.c :
	wget https://raw.githubusercontent.com/joshouamel/tools/master/src/cat/cat.c
getopt.c :
	wget https://raw.githubusercontent.com/joshouamel/tools/master/src/cat/getopt.c
getopt.h :
	wget https://raw.githubusercontent.com/joshouamel/tools/master/src/cat/getopt.h
